name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - "7.1"
          - "7.2"
          - "8.1"
      
    steps:
    - uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

#     - name: Validate composer.json and composer.lock
#       run: composer validate --strict

#     - name: Cache Composer packages
#       id: composer-cache
#       uses: actions/cache@v3
#       with:
#         path: vendor
#         key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#         restore-keys: |
#           ${{ runner.os }}-php-

    - name: Gcloud version
      run: gcloud --version
      
#     - name: Install dependencies
#       run: composer install --prefer-dist --no-progress
#     - name: run docker
#       run: docker-compose up -d & sleep 50
#     - name: pwd
#       run: pwd
#     - name: run tests
#       run: vendor/bin/phpunit
    
